name: ci

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: y0utubesir/mytestimg:test
  DOCKERFILE_PATH: ./Dockerfile-3-latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run Venv
        run: printenv
      -
        name: Run Venv
        run: echo ${TEST_TAG}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Print files out
        run: |
          ls -R -I.git?
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Build Test Image
        run: |
          docker build -t testimg ./testfiles/
      -
        name: Remove Test Image
        run: |
          echo "Test was successful, removing test image"
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64
          push: true
          tags: y0utubesir/mytestimg:latest
